### ISSUE TITLE
Sgt. Hammer links don't work

### ISSUE THREAD

**Issue by Trust** [diginc/HotSBuildCheatSheets#1]
All links on the Sgt. Hammer page go to an incorrect page.

Instead of: http://www.heroesfire.com/hots/talent-calculator/sgt.-hammer#hCE4
Should be: http://www.heroesfire.com/hots/talent-calculator/sergeant-hammer#hCE4

**Comment by diginc** [comment]
Thanks for the report!  

I updated the current stats urls and added a permanent fix.
