### ISSUE TITLE
Is Wiki up-to-date ?

### ISSUE THREAD

**Issue by Orabig** [diginc/HotSBuildCheatSheets#7]
It seems the wiki page has not been edited since february.
Is it still updated ?

**Comment by diginc** [comment]
Sorry but I haven't been playing much so hadn't updated.  It seems hots logs HTML is different enough now that the code needs to be tweaked some before an update could be pushed to the wiki.

**Comment by diginc** [comment]
Fixed the bug & updated wiki.

**Comment by Orabig** [comment]
Many thanks. That's a neat job you've done...
